apiVersion: v1
kind: Pod
metadata:
  name: poker
  labels:
    app: poker
spec:
  terminationGracePeriodSeconds: 0
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: poker
      image: quay.io/rajjoshi/poker:latest
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
        limits:
          cpu: "2"
          memory: 4Gi
  restartPolicy: Always
