apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-ucx-multiproc-hotfix
  labels:
    app.kubernetes.io/name: vllm-ucx-multiproc-hotfix
data:
  multiproc_executor.py: |
{{ .Files.Get "multiproc_executor.py" | nindent 4 }}
  vllm_net_devices.py: |
{{ .Files.Get "vllm_net_devices.py" | nindent 4 }}
  uniproc_executor.py: |
{{ .Files.Get "uniproc_executor.py" | nindent 4 }}
